# Site settings
title: Sensory Glove
email: sensoryglove@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Sensory Glove is a project designed to help the blind-deaf communicate
    with anybody.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "sensoryglove.github.io" # the base hostname & protocol for your site
github_username: sensoryglove

# Build settings
markdown: kramdown
